<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCLx7jce\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCLx7jce/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCLx7jce.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCLx7jce\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCLx7jce\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CLx7jce',
    'container.build_id' => '47a60ef6',
    'container.build_time' => 1635370023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCLx7jce');
